'use server'

import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { isSuperAdminUser } from '@/lib/auth/superadmin'
import { callDeepSeekChat } from '@/lib/deepseek'

// Internal tool only — QCypher staff spot-checking their own AI-generated
// blog content, not a tenant-facing feature. No persistence: this project
// has plenty of precedent for "no history/reporting" scoped-down tools
// (see Phase 37 v1's lack of admin analytics), and the spec this follows
// explicitly called for no database table.
async function requireSuperAdmin() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('Not authenticated')

  const admin = createAdminClient()
  const { data: { user: fresh } } = await admin.auth.admin.getUserById(user.id)
  if (!isSuperAdminUser(fresh)) throw new Error('Super admin only')

  return { user }
}

const SYSTEM_PROMPT = `You are an AI content detector. Analyze the provided text and estimate the likelihood it was generated by AI rather than written by a human.

Consider: repetitive sentence structure, unnaturally perfect grammar, generic/templated phrasing, lack of specific personal detail or anecdote, overly balanced "on one hand / on the other hand" framing, and vocabulary that reads as AI-typical.

This is a rough heuristic estimate for internal spot-checking, not a certified or forensic determination — a low or high score is a signal to look closer, not proof.

Respond with ONLY raw JSON, no markdown fences, no commentary: {"confidence": <integer 0-100, where 100 = certainly AI-generated>, "reasoning": "<one or two sentences>"}`

// Unauthenticated core — callable from other server actions (e.g. the
// tenant self-serve blog generator, which auto-checks its own AI output
// and has already done its own tenant-writer auth by the time it calls
// this). The super-admin-gated wrapper below is for the manual admin tool.
export async function analyzeAiConfidence(content: string): Promise<{ confidence: number; reasoning: string }> {
  const trimmed = content.trim()
  if (trimmed.length < 100) throw new Error('Content is too short to analyze meaningfully (100 characters minimum)')

  const raw = await callDeepSeekChat(
    [
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'user', content: `Analyze this content:\n\n${trimmed.slice(0, 4000)}` },
    ],
    { maxTokens: 250, temperature: 0.2 },
  )

  let parsed: unknown
  try {
    parsed = JSON.parse(raw)
  } catch {
    throw new Error('DeepSeek returned a non-JSON response — try again')
  }

  const { confidence, reasoning } = parsed as { confidence?: unknown; reasoning?: unknown }
  if (typeof confidence !== 'number' || typeof reasoning !== 'string') {
    throw new Error('DeepSeek response was missing confidence/reasoning fields')
  }

  return { confidence: Math.max(0, Math.min(100, Math.round(confidence))), reasoning }
}

export async function detectAiContent(content: string): Promise<{ confidence: number; reasoning: string }> {
  await requireSuperAdmin()
  return analyzeAiConfidence(content)
}
